config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :shoes do
    resources :bookings, only: [:new, :create]
  end
  get '/profile', to: 'pages#profile', as: 'profile'
end

# , only: [:index, :show, :new, :create]

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :shoe
end

app/models/shoe.rb
class Shoe < ApplicationRecord
  has_many :bookings, dependent: :destroy
  belongs_to :user

  validates :category, presence: true
  validates :address, presence: true
  has_one_attached :photo
  validates :photo, presence: true

  include PgSearch::Model
  pg_search_scope :search_by_title_brand_category_and_size,
    against: [ :title, :brand, :size, :category ],
    using: {
      tsearch: { prefix: true }
    }

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

# , inclusion: { in: ["hiking", "formal", "flippers", "sneakers", "wellies", "industrial", "climbing", "cycling", "sport"] }

app/models/user.rb
class User < ApplicationRecord
  has_many :shoes
  has_many :bookings
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
require "date"

class BookingsController < ApplicationController

  def new
    @booking = Booking.new
    @shoe = Shoe.find(params[:shoe_id])
  end

  def create
    @booking = Booking.create(duration: booking_duration, date: booking_date, user_id: current_user.id)
    # user_id needs to be changed once user functionality is implemented
    @booking.shoe = Shoe.find(params[:shoe_id])
    if @booking.save
      redirect_to profile_path, notice: 'Booking was successfully created.'
    # This path should be changed once user functionality is implemented
    else
      render :new
    end
  end

  private

  def booking_duration
    duration = params.require(:booking).permit(:duration)
    duration["duration"].to_i
  end

  def booking_date
    year = params.require(:booking).permit("date(1i)")
    month = params.require(:booking).permit("date(2i)")
    day = params.require(:booking).permit("date(3i)")
    date = Date.new(year["date(1i)"].to_i, month["date(2i)"].to_i, day["date(3i)"].to_i)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/shoes_controller.rb
class ShoesController < ApplicationController
  before_action :set_shoe, only: [:show, :edit, :update, :destroy]

  def index
    if params[:query].present?
      @shoes = Shoe.search_by_title_brand_category_and_size(params[:query])
      @markers = @shoes.geocoded.map do |shoe|
        {
          lat: shoe.latitude,
          lng: shoe.longitude
        }
      end
    else
      @shoes = Shoe.all
      @markers = @shoes.geocoded.map do |shoe|
        {
          lat: shoe.latitude,
          lng: shoe.longitude
        }
      end
    end
  end

  def new
    @shoe = Shoe.new
  end

  def edit
  end

  def destroy
    @shoe.destroy
    redirect_to profile_url, notice: 'Shoe was successfully deleted.'
  end

  def show
  end

  def create
    @shoe = Shoe.new(shoe_params)
    @user = current_user
    @shoe.user = @user

    if @shoe.save
      redirect_to @shoe, notice: 'Shoe was successfully created.'
    else
      render :new
    end
  end

  def update
    @shoe.update(shoe_params)
    if @shoe.update(shoe_params)
      redirect_to shoe_path(@shoe), notice: 'Shoe was successfully updated.'
    else
      render :edit
    end
  end

  private

  def set_shoe
    @shoe = Shoe.find(params[:id])
  end

  def shoe_params
    params.require(:shoe).permit(:title, :brand, :size, :category, :price, :image_url, :photo, :address)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/new.html.erb
  <div class="booking-shoe">
    <div id="image-book">
      <%= cl_image_tag @shoe.photo.key%>
    </div>
    <h2 id="booking-title" ><strong><%= @shoe.title %></strong></h2>
      <ul class="booking-lists">
        <li class="bokking-description" >Brand: <strong><%= @shoe.brand %></strong></li>
        <li class="bokking-description" >Size (UK): <strong><%= @shoe.size %></strong></li>
        <li class="bokking-description" >Type: <strong><%= @shoe.category %></strong></li>
        <li class="bokking-description" >Price: <strong><%= @shoe.price %>.00 </strong>/day</li>
      </ul>
  </div>

<div class="form-with-details">
  <div class="booking-form-div">
    <%= simple_form_for [@shoe, @booking], url: shoe_bookings_path, html: { class: "booking-form"} do |f|%>
      <%= f.input :date, as: :date, label: "Rental start date", :input_html => { class: 'field' } %>
      <%= f.input :duration, label: "Rental duration (days)", :input_html => { class: 'field' } %>

        <%= f.button :submit, 'Book now!',  class: "submit-button booking-submit"  %>

    <% end %>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Footwhere</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>

    <%# <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css"> %>
  </head>

  <body>
    <%= render 'pages/navbar'%>
    <% if notice %>
      <div class="flash alert alert-dismissible fade show" role="alert">
          <p><%= notice %></p>
        <a data-dismiss="alert" aria-label="Close">
          <i class="fas fa-times"></i>
        </a>
      </div>
    <% end %>

    <p class="alert"><%= alert %></p>

    <div class='content'>
      <%= yield %>
    </div>
    <%= render 'pages/footer'%>
  </body>

</html>

app/views/pages/_footer.html.erb
<div class='footer'>
  <ul class='footer-icons'>
    <li><i class="fab fa-facebook-square footer-icon"></i></li>
    <li><i class="fab fa-instagram-square footer-icon"></i></li>
    <li class='footer-footwhere'><%= link_to image_tag("PngItem_2089119.png", size:"50x50", class: "footer-image"), root_path %></li>
    <li><i class="fab fa-whatsapp-square"></i></li>
    <li><i class="fab fa-github-square"></i></li>
  </ul>
</div>

app/views/pages/_home_cards_div.html.erb
<div class="home-cards-div">
  <div class="cards-section">
    <h1 class="home-heading" id="how"><strong>How to use FootWhere!</strong></h1>

    <div class="three-cards-div">
        <div id="card-outershadow-home">
          <div class="card-home">
            <i class="fas fa-search"></i>
            <h4>🔍FIND!🔍</h4>
            <p>Find the FootWhere to suit your occasion.</p>
          </div>
        </div>

          <div class="arrow-home">
            <i class="fas fa-arrow-right"></i>
          </div>

        <div id="card-outershadow-home">
          <div class="card-home">
            <i class="fas fa-laptop"></i>
            <h4>🧑‍💻BOOK!🧑‍💻</h4>
            <p>Book them on the dates you need</p>
          </div>
        </div>

          <div class="arrow-home">
            <i class="fas fa-arrow-right"></i>
          </div>

        <div id="card-outershadow-home">
          <div class="card-home">
            <i class="fas fa-running"></i>
            <h4>📍WHERE!📍</h4>
            <p>Look and perform like a champion!</p>
          </div>
        </div>
    </div>

    <div>
        <a href="#second-scroll">
          <div class="down2">
            <div class="scroll-down2"></div>
          </div>
        </a>
    </div>

    <div>
      <p class="btn call-to-action"><%= link_to "See All Shoes", shoes_path %></p>
    </div>

  </div>


  <div class="cards-section-2" id="second-scroll">
    <h1 class="home-heading" id="how"><strong>How to make money with FootWhere!</strong></h1>

    <div class="three-cards-div">
        <div id="card-outershadow-home">
          <div class="card-home">
            <i class="fas fa-cloud-upload-alt"></i>
            <h4>💻 UPLOAD 💻</h4>
            <p>Upload your picture, add the shoes datails and publish!</p>
          </div>
        </div>

          <div class="arrow-home">
            <i class="fas fa-arrow-right"></i>
          </div>

        <div id="card-outershadow-home">
          <div class="card-home">
            <i class="fas fa-shipping-fast"></i>
            <h4>📦 DELIVER! 📦</h4>
            <p>Wait for the customer to pick up their order / send away!</p>
          </div>
        </div>

          <div class="arrow-home">
            <i class="fas fa-arrow-right"></i>
          </div>

        <div id="card-outershadow-home">
          <div class="card-home">
            <i class="fas fa-hand-holding-usd"></i>
            <h4>💸 EARN 💸</h4>
            <p> Get cash from your unused shoes </p>
          </div>
        </div>
    </div>

    <div>
      <p class="btn call-to-action-2"><%= link_to "Create your first shoe!", new_shoe_path %> </p>
    </div>
  </div>

</div>

app/views/pages/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon" id="sticky">
  <div class="navbar-left-icon">
    <%= link_to root_path, class: "navbar-brand" do %>

    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= image_tag ("PngItem_2089119.png") %>
      </li>
        <br>
      <li class="nav-item">
      <h2>FootWhere?</h2>
      </li>
    </ul>
    <% end %>
  </div>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "All Shoes", shoes_path, class: "nav-link" %>
      </li>
      <% if user_signed_in? %>
      <li class="nav-item">
        <%= link_to "Hi #{current_user.email}", profile_path, class: "nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <%= image_tag "https://kitt.lewagon.com/placeholder/users/random", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "My profile", profile_path, class: "dropdown-item" %>
          <%= link_to "Settings", "#", class: "dropdown-item" %>
          <%= link_to "Log out", destroy_user_session_path, class: "nav-link" , method: :delete %>
        </div>
      </li>
      <% else %>
      <li class="nav-item active">
        <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
      </li>
      <li class="nav-item active">
        <%= link_to "Log in", new_user_session_path, class: "nav-link" %>
      </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://thumbor.forbes.com/thumbor/960x0/https%3A%2F%2Fspecials-images.forbesimg.com%2Fimageserve%2F5efca684531e1500073c686a%2FRunning-Shoes-On-Running%2F960x0.jpg%3Ffit%3Dscale);">
  <div class="container banner-text">
    <h1>FootWhere?</h1>
    <p class="description-text">Get the perfect pair for that one off occasion or share yours with the world!</p>
    <p class="btn btn-flat"><%= link_to "See All Shoes", shoes_path %> </p>
    <a href="#first-scroll">
      <div class="scroll-down"></div>
    </a>
    <div id="first-scroll"></div>
  </div>
</div>

<%= render 'home_cards_div'%>

app/views/pages/profile.html.erb
<div class="container">

  <div class="row justify-content-center">
    <div class="col-sm-12">
      <br>
      <h1><%="Hi #{current_user.email}, this is your profile page!"%></h1>
      <br>
      <p class="row justify-content-center">Here you can see all of your current rentals and bookings, edit their details and see your previous rentals and bookings.</p>
      <br>
      <br>
    </div>
  </div>


  <h3> My Rentals </h3>
  <%if Booking.where( { user_id: current_user.id} ).to_a == []%>
    <br>
    <h5>It looks like you haven't rented any shoes yet!</h5>
    <br>
    <p class="btn btn-flat"><%= link_to "Rent shoes now!", shoes_path %> </p>
    <br>
    <br>
    <br>
  <%else %>
    <div class="cards" style="padding: 0px;">
      <% @user_bookings = Booking.where( { user_id: current_user.id} ).to_a %>
      <% @user_bookings.each do  |booking| %>
        <% @shoe = Shoe.find_by id: booking.shoe_id %>
        <%= link_to shoe_path(@shoe) do %>
          <div class="card-shoe-profile">
            <%= cl_image_tag @shoe.photo.key %>
            <div class="card-shoe-profile-infos">
              <div>
                <h2><%= @shoe.title %></h2>
                <p>Title: <strong><%= @shoe.title %></strong></p>
                <p>When: <strong><%= booking.date %>.00 </strong>/day</p>
                <p>For: <strong><%= booking.duration %> days</strong></p>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  <%end% %>

  <h3> My Shoes </h3>
  <div class="cards" style="padding: 0px;">
    <%= link_to new_shoe_path do %>
      <div class="card-shoe-add" id="new-shoe-card">
        <i class="far fa-plus-square"></i>
      </div>
    <% end %>

    <% @user_shoes = Shoe.where( { user_id: current_user.id} ).to_a %>
    <% @user_shoes.each do |shoe| %>


        <div class="card-shoe-profile">
          <%= link_to edit_shoe_path(shoe) do %>
            <div class="card-icon" >
              <i class="fas fa-edit" id="edit-icon"></i>
            </div>
          <% end %>
          <%= link_to shoe_path(shoe), method: :delete, data: { confirm: "Are you sure?" } do %>
            <div class="card-icon" >
              <i class="fas fa-trash-alt" id="delete-icon"></i>
            </div>
          <% end %>

          <%= cl_image_tag shoe.photo.key %>


          <div class="card-shoe-profile-infos">
            <div>
              <%= link_to shoe_path(shoe) do %>
                <h2><%= shoe.title %></h2>
              <% end %>
              <br>
              <p>Brand: <strong><%= shoe.brand %></strong></p>
              <p>Size (UK): <strong><%= shoe.size %></strong></p>
              <p>Type: <strong><%= shoe.category %></strong></p>
              <p>Price: <strong><%= shoe.price %>.00 </strong>/day</p>
            </div>
          </div>
        </div>

    <% end %>
  </div>
  <br>
  <br>
  <br>

</div>

app/views/shoes/edit.html.erb
<div class="booking-form-div">
    <%= simple_form_for @shoe, html: { class: "booking-form"} do |f|%>
      <%= f.input :title, label: "Title (15 Characters Max)", :input_html => { class: 'field' } %>
      <%= f.input :brand, label: "Brand", :input_html => { class: 'field' } %>
      <%= f.input :size, label: "Size", :input_html => { class: 'field' } %>
      <%= f.input :photo, as: :file %>
      <%= f.input :category, collection: ["hiking", "formal", "flippers", "sneakers", "wellies", "industrial", "climbing", "cycling", "sport"], label: "Category", :input_html => { class: 'field' } %>
      <%= f.input :price, label: "Price (£)", :input_html => { class: 'field' } %>
      <%= f.input :address, label: "Shoe location (Street Address, Town/City)", :input_html => { class: 'field' } %>
      <%= f.button :submit, 'Save Changes',  class: "submit-button booking-submit"  %>
    <% end %>
  </div>

<%# Put below statement on the show page ?  %>
<%# <%= link_to 'Edit', edit_shoe_path(@shoe) %>

<%# Code for deleting a shoe ?  %>
<%# <%= link_to "Delete Shoe", shoe_path(shoe), method: :delete, data: { confirm: "Are you sure?" } %>

app/views/shoes/index.html.erb
<div class="search-container">
    <%= form_tag shoes_path, method: :get, class: 'form-inline' do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control flex-grow-1",
        placeholder: "Find your perfect FootWhere"
      %>
      <%= submit_tag "Search", class: "btn btn-search" %>
    <% end %>
</div>

<div class="map-shoes-container">
  <div class="shoes-div">
    <% @shoes.each do |shoe| %>
      <%= link_to shoe_path(shoe) do %>
        <div class="shoe-info-index">

            <div class="image">
              <%= cl_image_tag shoe.photo.key, height: 250, width: 250, class:"image"%>
            </div>


              <div class="shoe-title">
                <p class="title" ><%= shoe.title %></p>
              </div>

              <div class="card-text-p">
                <ul class="details">
                  <li class="detail" >Brand: <strong><%= shoe.brand %></strong></li>
                  <li class="detail" >Size (UK): <strong><%= shoe.size %></strong></li>
                  <li class="detail" >Type: <strong><%= shoe.category %></strong></li>
                  <li class="detail" >Price: <strong>£<%= shoe.price %>.00 </strong>/day</li>
                </ul>
              </div>


             <%unless shoe.latitude%>
              <span class="marker-warning">Map location unavailable</span>
             <%end%>

        </div>
      <% end %>
      <br>
    <% end %>
  </div>
  <div id = "map" class="map-div" data-controller="mapbox"
  data-mapbox-markers-value="<%= @markers.to_json %>"
  data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>

app/views/shoes/new.html.erb
  <div class="booking-form-div">
    <%= simple_form_for @shoe, url: shoes_path, html: { class: "booking-form"} do |f|%>
      <%= f.input :title, label: "Title (15 Characters Max)", :input_html => { class: 'field' } %>
      <%= f.input :brand, label: "Brand", :input_html => { class: 'field' } %>
      <%= f.input :size, label: "Size", :input_html => { class: 'field' } %>
      <%= f.input :photo, as: :file %>
      <%= f.input :category, collection: ["hiking", "formal", "flippers", "sneakers", "wellies", "industrial", "climbing", "cycling", "sport"], label: "Category", :input_html => { class: 'field' } %>
      <%= f.input :price, label: "Price (£)", :input_html => { class: 'field' } %>
      <%= f.input :address, label: "Shoe location (Street Address, Town/City)", :input_html => { class: 'field' } %>
      <%= f.button :submit, 'Save',  class: "submit-button booking-submit"  %>
    <% end %>
  </div>

app/views/shoes/show.html.erb
<div class="container" style="padding-top: 50px;">

  <div class="container-show">
    <div class="product-image">
      <p class="shoe-show-img"><%= cl_image_tag @shoe.photo.key, width: 600, crop: :fill%></p>
    </div>

    <div class="information">
      <h2><strong><%= @shoe.title %></strong></h2>
      <div class="information-price">
        <h3><strong>£<%= @shoe.price %>.00 </strong>/day</h3>
      </div>
      <div class=" book-now">
        <%= link_to "BOOK NOW", new_shoe_booking_path(@shoe.id) %>
      </div>
      <div class="information-content">
        <p><strong>Size:</strong> <%= @shoe.size %></p>
        <p><strong>Brand:</strong> <%= @shoe.brand %></p>
        <p><strong>Category:</strong> <%= @shoe.category %></p>
        <h5>✅ Available for pick up!</h5>
      </div>
    </div>
  </div>

  <br>

  <div style="padding-left: 60px;">
    <div class="btn btn-flat" style="background-color:white; border-color: #add8e6;">
      <%= link_to "back", shoes_path %>
    </div>
  </div>

  <br>

</div>

app/views/users/show.html.erb
<h1>This is the users page</h1>

Go to the index page

<div class="container">
  <h3>My bookings:</h3>
  <div class="cards">
      <% @bookings.each do |booking| %>
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(#)">
          <%= booking.shoe_id %>
        </div>
      <% end %>
  </div>
</div>


My listings



<%= link_to "<- home", root_path%>